version: "3"
services:

  ngwp-ng:
    image: nginx
    networks: 
      - frontend
    volumes:
      - /home/azrin/project/g8/ngwp/ngwp-ng/dist/ngwp-ng:/usr/share/nginx/html
    ports: 
      - "80:80"

  ngwp-mongo:
    image: mongo
    restart: always
    volumes:
      - /home/azrin/project/g8/ngwp/ngwp-mongo:/etc/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ngwpadmin
      MONGO_INITDB_ROOT_PASSWORD: Engine1
    ports:
      - "27017:27017"
  
  ngwp-wp:
    image: wordpress:latest
    networks: 
      - backend
    depends_on:
      - ngwp-mysql
    volumes: 
       - /home/azrin/project/g8/ngwp/ngwp-wp:/var/www/html
    restart: always
    ports: 
      - "8000:80"  
    environment:
      WORDPRESS_DB_HOST: ngwp-mysql:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: Engine1@
      WORDPRESS_DB_NAME: wp_db
  
  ngwp-mysql:
    image: mysql:5.7
    volumes: 
      - /home/azrin/project/g8/ngwp/ngwp-mysql:/var/lib/mysql
    networks: 
      - backend
    restart: always    
    environment:
      MYSQL_ROOT_PASSWORD: gouk560      
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: Engine1@
      MYSQL_DATABASE: wp_db

networks:
  frontend:
  backend:
