version: "3"
services:

  ngwp-ng:
    image: nginx
    networks: 
      - frontend
    volumes:
      - "/home/azrin/project/ngwp/ngwp-ng/dist/ngwp-ng:/usr/share/nginx/html"
    ports: 
      - "80:80"
  
  ngwp-wp:
    image: wordpress:latest
    networks: backend
    depends_on:
      - ngwp-mysql
    ports: 
      
