version: "3"
services:

  ngwp-ng:
    image: nginx
    networks: 
      - frontend
    volumes:
      - "/home/azrin/project/ngwp/ngwp-ng/dist/ngwp-ng:/usr/share/nginx/html"
    ports: 
      - "80:80"
  
  ngwp-wp:
    image: wordpress:latest
    networks: backend
    depends_on:
      - ngwp-mysql
    volume: 
       - "/home/azrin/project/ngwp/ngwp-wp:/usr/share/nginx/html"
   
    ports: 
      - "8000:80"  
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: examplepass
      WORDPRESS_DB_NAME: exampledb
