<?php
$pointers = array();
$pointers['miniorange-support-pointer'] = array(
    'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'We are here!!' ) ),
    'content'   => sprintf( '<p>%s</p>', esc_html__( 'Get in touch with us and we will help you setup the plugin in no time.' ) ),
    'anchor_id' => '#mo_support_layout',
    'edge'      => 'right',
    'align'     => 'left',
    'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
);

if(isset($_GET['action'])) {
    if($_GET['action'] === 'add') {
        $pointers['miniorange-client-name-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'Client Name' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Type in the Name you want to assign this client application.' ) ),
            'anchor_id' => '#client_name',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
        $pointers['miniorange-client-redirect-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'Client Redirect/Callback URI' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Type in a Redirect/Callback URI that your Client Application will use' ) ),
            'anchor_id' => '#redirect_uri',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
        $pointers['miniorange-client-save-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'Saving Settings' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Save the settings to Register a Client Application' ) ),
            'anchor_id' => '#client_save',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
    }
}

if(isset($_GET['tab'])) {
    if((isset($_GET['tab']) && $_GET['tab'] === 'config')) {
        $pointers['miniorange-add-client-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'Adding/Registering A Client' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Click here to Add/Register a Client Application.' ) ),
            'anchor_id' => '#add_client',
            'edge'      => 'right',
            'align'     => 'left',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
        $pointers['miniorange-howtosetup-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'How to Setup?' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'These are the endpoints and scopes you need to provide your client so that you can use your WordPress Site for Single Sign-On!' ) ),
            'anchor_id' => '#how_to_setup',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
    }
    if(isset($_GET['tab']) && $_GET['tab'] === 'general_settings') {
        $pointers['miniorange-master-switch-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'The Master Switch' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'This control allows you to enable or disable the functionality of the server' ) ),
            'anchor_id' => '#master_switch',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
        $pointers['miniorange-general-settings-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'General Settings' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Here, you can configure Token Length as well as Token Expiry times, which specifies after how many seconds will the Tokens generated by the server will expire.' ) ),
            'anchor_id' => '#generalsettings',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
        $pointers['miniorange-state-parameter-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'The State Parameter' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Here, you can configure the State Parameter. It is used as a security parameter while making requests to check that the requests themselves are valid!' ) ),
            'anchor_id' => '#enforce_state',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
        $pointers['miniorange-redirect-validation-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'Redirect/Callback URI Validation' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Here, you can configure if the Redirect/Callback URI in a request must be validated.' ) ),
            'anchor_id' => '#redirect_validation',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
    }
    if(isset($_GET['tab']) && $_GET['tab'] === 'attributemapping') {
        $pointers['miniorange-basic-attr-mapping-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'Basic Attribute Mapping' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Here, you can configure which attributes the server should send from your WordPress site, for a user trying to perform SSO.' ) ),
            'anchor_id' => '#basicattributemapping',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
        $pointers['miniorange-attr-mapping-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'Custom Attribute Mapping' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Here, you can configure the server to send more attributes from your WordPress site.' ) ),
            'anchor_id' => '#attributemapping',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
    }
    if(isset($_GET['tab']) && $_GET['tab'] === 'advanced_settings') {
        $pointers['miniorange-enable-oidc-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'OpenID Connect' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Here, you can choose if you want to enable OpenID Connect Flow. OAuth Flow will still work if it is enabled.' ) ),
            'anchor_id' => '#enable_oidc',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
        $pointers['miniorange-advanced-settings-pointer'] = array(
            'title'     => sprintf( '<h3>%s</h3>', esc_html__( 'Advanced Settings' ) ),
            'content'   => sprintf( '<p>%s</p>', esc_html__( 'Here, you can configure settings related to Grant Types, JWT Support and Signing Algorithms.' ) ),
            'anchor_id' => '#advancedsettings',
            'edge'      => 'left',
            'align'     => 'right',
            'where'     => array( 'toplevel_page_mo_oauth_server_settings' ) // <-- Please note this
        );
    }
}
return $pointers;
